$(function(){
	$(".btn1").on("click",function(){
		$("ul").append("<li>"+$("#h31").text()+"</li>")
	})
	$(".btn2").on("click",function(){
		$("ul").append("<li>"+$("#h32").text()+"</li>")
	})
	$(".btn3").on("click",function(){
		$("ul").append("<li>"+$("#h33").text()+"</li>")
	})
	$(".btn4").on("click",function(){
		$("ul").append("<li>"+$("#h34").text()+"</li>")
	})
	$(".btn5").on("click",function(){
		$("ul").append("<li>"+$("#h35").text()+"</li>")
	})
	$(".btn6").on("click",function(){
		$("ul").append("<li>"+$("#h36").text()+"</li>")
	})
	$()
})